version: '3.3'
services:
  beacon:
    build:
      context: ./lighthouse/build
      args:
        BASE_IMAGE:  $LIGHTHOUSE_IMAGE
        PROCESS_UID: $BEACON_UID
        PROCESS_GID: $BEACON_GID
    environment:
      - CONSENSUS_DISC
    ports:
      - "${CONSENSUS_DISC}:${CONSENSUS_DISC}/tcp"
      - "${CONSENSUS_DISC}:${CONSENSUS_DISC}/udp"
      - "127.0.0.1:5052:5052"
    volumes:
      - ./lighthouse/beacon/run:/home/consensus/run
      - ./shared:/shared
    depends_on:
      - execution
    networks:
      - lighthouse_stake

networks:
  lighthouse_stake:
    name: lighthouse_stake
    driver: bridge
