version: '3'
services:
  execution:
    build:
      context: ./${EXECUTION_NODE}/build
      args:
        BASE_IMAGE:  'hyperledger/besu:22.7.1'
        PROCESS_UID: 1000
        PROCESS_GID: 1000
    environment:
      - EXECUTION_DISC
    ports:
      - "${EXECUTION_DISC}:${EXECUTION_DISC}/tcp"
      - "${EXECUTION_DISC}:${EXECUTION_DISC}/udp"
    expose:
      - 8545
      - 8560
    volumes:
      - ./${EXECUTION_NODE}/run:/home/execution/run
      - ./shared:/shared

