version: '3.3'
services:
  execution:
    build:
      context: ./${EXECUTION_NODE}/build
      args:
        PROCESS_UID: $EXECUTION_UID
        PROCESS_GID: $EXECUTION_GID
        BESU_IMAGE: $BESU_IMAGE
        NETHERMIND_IMAGE: $NETHERMIND_IMAGE
    environment:
      - EXECUTION_DISC
    ports:
      - "${EXECUTION_DISC}:${EXECUTION_DISC}/tcp"
      - "${EXECUTION_DISC}:${EXECUTION_DISC}/udp"
    expose:
      - 8545
      - 8560
    volumes:
      - ./${EXECUTION_NODE}/run:/home/execution/run
      - ./shared:/shared
    networks:
      - lighthouse_stake
