services:
  beacon:
    environment:
      - METRICS_ENABLED=true
    expose:
      - 5054
  validator:
    environment:
      - METRICS_ENABLED=true
    expose:
      - 5064
  execution:
    environment:
      - METRICS_ENABLED=true
    expose:
      - 6060
  prometheus:
    build:
      context: ./metrics/build/prometheus
      args:
        BASE_IMAGE:  'prom/prometheus'
        PROCESS_UID: $METRICS_UID
        PROCESS_GID: $METRICS_GID
    ports:
      - "127.0.0.1:${PROMETHEUS_PORT}:9090/tcp"
    expose:
      - 9090
    volumes:
      - ./metrics/run/prometheus/:/home/promuser/run
    depends_on:
      - execution
      - beacon
    networks:
      - lighthouse_stake
  grafana:
    build:
      context: ./metrics/build/grafana
      args:
        BASE_IMAGE:  'grafana/grafana'
        PROCESS_UID: $METRICS_UID
        PROCESS_GID: $METRICS_GID
    ports:
      - "127.0.0.1:${GRAFANA_PORT}:3000/tcp"
    environment:
      - GF_PATHS_DATA=/home/grafuser/run/data
      - GF_PATHS_LOGS=/home/grafuser/run/data
    volumes:
      - ./metrics/run/grafana/:/home/grafuser/run
    depends_on:
      - prometheus
    networks:
      - lighthouse_stake

  nut_exporter:
    image: druggeri/nut_exporter
    environment:
      NUT_EXPORTER_PASSWORD: export
      NUT_EXPORTER_VARIABLES: >
        battery.charge,battery.runtime,battery.runtime.low,
        battery.voltage,battery.voltage.nominal,
        input.voltage,input.voltage.nominal,
        ups.load,ups.status,ups.realpower.nominal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - --nut.server=host.docker.internal
      - --nut.username=prometheus
    ports:
      - "127.0.0.1:9199:9199"
    networks:
      - lighthouse_stake

  node_exporter:
    image: prom/node-exporter:latest
    command:
      - --path.rootfs=/host
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
    expose:
      - 9100
    ports:
      - "127.0.0.1:9100:9100"
    networks:
      - lighthouse_stake
