version: '3.3'
services:
  beacon:
    environment:
      - MEVBOOST_ENABLED=true
  validator:
    environment:
      - MEVBOOST_ENABLED=true
  mev-boost:
    build:
      context: ./mev-boost/build
      args:
        BASE_IMAGE:  $MEVBOOST_IMAGE
        PROCESS_UID: $MEVBOOST_UID
        PROCESS_GID: $MEVBOOST_GID
    expose:
      - 8560
    volumes:
      - ./mev-boost/run:/home/boost/run
    depends_on:
      - execution
      - beacon
    networks:
      - lighthouse_stake
