version: '3.3'
services:
  validator:
    build:
      context: ./lighthouse/build
      args:
        BASE_IMAGE:  'sigp/lighthouse:latest'
        PROCESS_UID: 1000
        PROCESS_GID: 1000
    environment:
        - ENCRYPTED_SECRETS_DIRECTORY
        - METRICS_ENABLED
    volumes:
      - type: bind
        source: ./lighthouse/validator/run
        target: /home/consensus/run
        bind:
          propagation: rslave
    depends_on:
      - beacon
