version: '3.3'
services:
  validator:
    build:
      context: ./lighthouse/build
      args:
        BASE_IMAGE:  $LIGHTHOUSE_IMAGE
        PROCESS_UID: $VALIDATOR_UID
        PROCESS_GID: $VALIDATOR_GID
    environment:
        - ENCRYPTED_SECRETS_DIRECTORY
        - METRICS_ENABLED
    volumes:
      - type: bind
        source: ./lighthouse/validator/run
        target: /home/consensus/run
        bind:
          propagation: rslave
    depends_on:
      - beacon
    networks:
      - lighthouse_stake
