global:
    scrape_interval: 15s

scrape_configs:
  - job_name: 'beacon'
    static_configs:
      - targets: ['beacon:5054']
  - job_name: 'validator'
    static_configs:
      - targets: ['validator:5064']
  - job_name: 'execution'
    static_configs:
      - targets: ['execution:6060']

  - job_name: 'nut'
    metrics_path: /ups_metrics
    static_configs:
      - targets: ['nut_exporter:9199']
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

